### ISSUE TITLE
Unknown error connecting

### ISSUE THREAD

**Issue by matata86** [kukulich/home-assistant-aladin-online#1]
Ahoj Jardo,
hází toto...

`Logger: custom_components.aladin_online
Source: custom_components/aladin_online/config_flow.py:66
Integration: Aladin online (Czech Republic) (documentation, issues)
First occurred: 9:33:04 (2 occurrences)
Last logged: 9:35:19

Unknown error connecting to https://aladinonline.androworks.org/get_data.php?latitude=50.752107224693475&longitude=15.03373056650162`

**Comment by kukulich** [comment]
Prostě nefunguje ten zdroj dat.
