### ISSUE TITLE
Implementation of get_forecasts providing weird results (HA 2024.4)

### ISSUE THREAD

**Issue by tristone-cz** [kukulich/home-assistant-aladin-online#10]
Hi.

A bit long and tough to explain.

### Background ###
As HA 2024.4 deprecated the old forecast attribute there must be different ways how to deal with weather templates to ensure eg. values rounding.
Now new weather template entity cannot be created directly using the source weather entity. First there must be created a template sensor with attribute forecast and based on this sensor it is possible to create new template weather entity.
A lot of discussions about this in the forum.

### Problem ###
Once passing through the above approach with Aladin and Openweathermap (for comparison) it works fine for OWM but not working for the Aladin.
For the first look it looks OK but there is no forecast for the new template weather entity created for Aladin. Even if the original entities are fine.

### Details ###
First , both weather entities created by Aladin and OWM integrations are fine. 
![original_weather_entities](https://github.com/kukulich/home-assistant-aladin-online/assets/40542489/cb2a4607-7d93-4d71-9a2b-4d9fa8855f9e)

Second, the template sensors contains the forecast data but looks different in States page. This is already suspicious. The list for Aladin seems not be OK.
Definition of those sensors (both exactly the same, just different source weather entity):
[template_sensors_definition.txt](https://github.com/kukulich/home-assistant-aladin-online/files/14916983/template_sensors_definition.txt)
Resulted in:
![tempalte_sensors](https://github.com/kukulich/home-assistant-aladin-online/assets/40542489/b7a60ec3-f369-4192-8704-05b18b417343)

Third, new template weather entities created from above sensors resulted in the difference and problem for Aladin. OWM entity is fine, rounded. Aladin entity does not contain any forecast.
Definition of those entities (both exactly the same, just different source sensor entity):
[template_weather_definition.txt](https://github.com/kukulich/home-assistant-aladin-online/files/14917031/template_weather_definition.txt)
Resulted in:
![rounded_weather_entities](https://github.com/kukulich/home-assistant-aladin-online/assets/40542489/ba29398e-4245-4d9e-8bc8-96b2c52d0460)

There is an error in HA once trying to create template weather from the Aladin sensor.
```Error validating template result ...... from template 'Template<template=({{ state_attr('sensor.weather_domov_aladin', 'forecast') }}) renders=6>' for attribute '_forecast_hourly' in entity weather.weather_domov_aladin validation message 'Forecasts is not a list ```
Full log line:
[HA_error_forecast_hourly.txt](https://github.com/kukulich/home-assistant-aladin-online/files/14916943/HA_error_forecast_hourly.txt)

So it seems to that somehow the get forecasts functionality is not producing correctly a list in Python. Even if I do not understand why the Aladin entity itself work but once the data are being used elsewhere it is not.

The ```weather.get_forecasts``` output looks fine for both Aladin and OWM:
[get_forecasts.txt](https://github.com/kukulich/home-assistant-aladin-online/files/14916944/get_forecasts.txt)

I tried to went through the code but I am not Python programmer, found nothing usefull.
Available for testing.

**Comment by kukulich** [comment]
Please try dev version.

**Comment by tristone-cz** [comment]
I tried latest version but no change in behavior. Both sensor and weather behaves the same.
Weather.py was updated:
![image](https://github.com/kukulich/home-assistant-aladin-online/assets/40542489/567d8b8f-23aa-4210-abce-9ab1530d55ea)

**Comment by kukulich** [comment]
@tristone-cz Have you clear the pycache ?

**Comment by tristone-cz** [comment]
Initially I forgot. But now I deleted the pycache for the Aladin integration and after restart still no change 😢

**Comment by kukulich** [comment]
I think it does not make sense to try to get the data by the attribute: https://github.com/home-assistant/core/commit/65230908c6bd7b9f2dac6e8de41b7bd27d28d1be

**Comment by tristone-cz** [comment]
Yes. The forecast attribute was removed from the Weather entity since HA 2024.4

This broke the way how many people was dealing more with the data (rounding, extracting just some values, etc.) - use the forecast attribute as an input for weather template (fields forecast_hourly_template , forecast_daily_template).
The workaround is to extract the forecast content using get_forecasts service into a sensor, not a weather, entity. And using the sensor it is possible again to fill in the weather template fields.

And the thing is that the extraction to the sensor is not working as expected by Aladin integration (and following the discussions, some others as well I would say). The output seems not to be understood as a list.

So far I haven't seen anyone to found another way than the weather entity -> sensor with forecast attribute -> new template weather.

**Comment by tristone-cz** [comment]
One hint I got in another thread at the forum:

_Which weather integration are you using?_

_The reason why I am asking is because it’s reporting dates as datetime objects instead of datetime strings.__
![image](https://github.com/kukulich/home-assistant-aladin-online/assets/40542489/8079e352-1221-46d4-b2d3-f73e217887b8)

**Comment by kukulich** [comment]
@tristone-cz I don't understand because you try to use `{{ state_attr('sensor.weather_domov_aladin', 'forecast') }}` and it uses the deprecated `forecast` attribute.

**Comment by tristone-cz** [comment]
@kukulich Yes, but it's forecast attribute of a sensor entity, not a weather entity.

That's the workaround trick. Using service call `get_forecasts` fill an artificial sensor, which can have forecast attribute, why not. And once we have this attribute, we can fill the `forecast_hourly_template` field of weather template.

Annoying, uncomfortable , etc. etc. But at least in principle working 😄

**Comment by kukulich** [comment]
https://github.com/kukulich/home-assistant-aladin-online/commit/4f813d13d11d0c730e1351b5f736579bac7e2029 - don't know if it will help.

**Comment by tristone-cz** [comment]
> [4f813d1](https://github.com/kukulich/home-assistant-aladin-online/commit/4f813d13d11d0c730e1351b5f736579bac7e2029) - don't know if it will help.

This one works 🥳 🍾 
Thanks a lot.

**Comment by TomasApeltauer** [comment]
@tristone-cz : Can you please share the correct form of the template sensor that would solve the problem? I'm trying to build a sensor that would contain a time series forecast for some quantity, e.g. temperature or wind speed. Thank you :-)
