### ISSUE TITLE
Hodinová předpověď

### ISSUE THREAD

**Issue by Konycz** [kukulich/home-assistant-aladin-online#11]
Dobrý den, je nějaká možnost získat hodinovou předpověď do Entit ?? A tím i další otázka, a to získání nejvyšší a nejnižší předpovědi pro aktuální den.

**Comment by kukulich** [comment]
Pomocí `template` integrace určitě.

**Comment by Konycz** [comment]
Tak to vubec nemam tuseni jak na to :)
mohl bych poprosit o nejaky navod ?
