### ISSUE TITLE
Posunuta predpoved

### ISSUE THREAD

**Issue by brozikcz** [kukulich/home-assistant-aladin-online#13]
Ahoj, vypada to, ze pri zmene https://github.com/kukulich/home-assistant-aladin-online/commit/e5e892612932d0712b0529ace24126b7ef4f28bb se rozbilo formatovani / nastaveni nasi casove zony. Ted ukazuje predpoved o 2h spatne do zadu.
Jako kdyby se `dt.set_default_time_zone(timezone)` vubec nebrala v potaz.
Nemam tuseni jak to opravit, proto issue.

Uz jsem se do toho slusne zamotal a nevim, jestli problem je v indexu a nebo timezone, kazdopadne tohle to resi (chapu, ze to neni fix a resi to jen predpoved po hodinach)

```
	@staticmethod
	async def _format_datetime(raw: str) -> datetime:
		timezone = await dt.async_get_time_zone("Europe/Prague")
		dt.set_default_time_zone(timezone)
		return dt.parse_datetime(raw) - timedelta(hours=2)
```

edit:

tohle to asi resi, ale zas si stezuje na IO pri volani pytz
```
		return pytz.timezone("Europe/Prague").localize(datetime.fromisoformat(raw)).astimezone(pytz.utc).replace(tzinfo=None)

```

**Comment by kukulich** [comment]
Opraveno ve verzi 2.8.0.
