### ISSUE TITLE
Data před aktuálním časem

### ISSUE THREAD

**Issue by DavidAntonin** [kukulich/home-assistant-aladin-online#15]
Bylo by možné zpřístupnit data před aktuálním časem? Tak jako to má android aplikace - nyní ve 12h vidím ještě i data od půlnoci. Nebo aspoň aby bylo daty pokryto aspoň celých 48h.

**Comment by kukulich** [comment]
![Snímek obrazovky 2024-08-22 124314](https://github.com/user-attachments/assets/4784a66b-f5f8-4891-be3f-488b59a60231)

Já tam mám data už teď :)

**Comment by kukulich** [comment]
Jo, aha. Blbě jsem pochopil otázku - jako mít tam i stará data?

**Comment by DavidAntonin** [comment]
Přesně tak, teď tam jsou data do soboty 7:00, tak mít data od dnešních 7:00

**Comment by kukulich** [comment]
Vydáno ve verzi 2.8.0
