### ISSUE TITLE
Možnost nastavení intervalu updatu / Set interval update

### ISSUE THREAD

**Issue by Rumlik** [kukulich/home-assistant-aladin-online#16]
Ahoj,
šla by udělat možnost upravit (vybrat) si z rychlejších aktualizací (interval update). Aktuálně, co jsem vypozoroval, je to 1h, je to tak?

Díky
-----
Hi,
could you make it possible to edit (choose) from faster updates (update interval). Currently, from what I have observed, it is 1h, right?

Thank you :)

**Comment by kukulich** [comment]
Nejsem si jist, co je tím myšleno. Ale ve zdroji jsou data akorát po hodinách a zveřejněna asi 2x nebo 4x denně.

**Comment by Rumlik** [comment]
Myslel jsem tím například aktuální teplota. Aktualizuje se jen po 1h.  Ruční znovu načtení samozřejmě aktualizuje hned kdykoliv.

**Comment by kukulich** [comment]
No, asi se tam dá nastavit minuta, čímž se zajistí, že se data posunou/aktualizují každou celou hodinu.

**Comment by Rumlik** [comment]
No to je ta aktualizace po hodině. Ale šlo by to dřív?
Za hodinu přijde bouřka, déšť a teplota nebude 30 ale 18 a hodinu bude trvat než se načte update. Rozumíme si.

**Comment by kukulich** [comment]
Ale tam žádná novější data nejsou. Aladin je zveřejňuje 4x za den.

**Comment by Rumlik** [comment]
Aha, tak to asi byla náhoda že zrovna tam byla na Aladinu novější data :) jasně tak potom škoda Aladin je pro mě na nic na automatizace

**Comment by kukulich** [comment]
CHMU ma nově opendata, která budu teprve zkoumat, zda se nedají využít, ale i dle nich to vypadá, že data pro dnešní 18-23 hodinu jsou napočítána včera: https://opendata.chmi.cz/meteorology/weather/nwp_aladin/CZ_1km/
