### ISSUE TITLE
Začátek hodinové předpovědi

### ISSUE THREAD

**Issue by tomasbedrich** [kukulich/home-assistant-aladin-online#19]
Hodinová předpověď vždy začíná od 00:00. To způsobuje, že když se vybere Aladin entita jako zdroj hodinových dat pro např. výchozí Weather card na Dashboardu, data jsou vždy zobrazena od 00:00 daného dne, i když je např. 9:00 ráno.

Očekávané chování: stejně jako Met.no integrace - postupně odstraňuje uplynulé hodiny z dat entity.

**Comment by kukulich** [comment]
Opraveno v nejnovějším releasu.
