### ISSUE TITLE
2.8.1 posunutá předpověď

### ISSUE THREAD

**Issue by DavidAntonin** [kukulich/home-assistant-aladin-online#21]
Předpověď je posunutá o 2h, tedy maximální teplota je v 13h a správně by měla být v 15h
Pro porovnání s webem CHMI Aladin
![aladin](https://github.com/user-attachments/assets/ade2aec5-0973-4d50-9bf8-fb28222a1b32)

**Comment by kukulich** [comment]
Přijde mi, že screenshot z HA a graf z https://aladinonline.androworks.org/ odpovídají. Třetí graf nevím, odkud je, ale ani nevím, proč by měl být relevantní.

**Comment by DavidAntonin** [comment]
Třetí graf je přímo z CHMI - Aladin. A stejně tak je posun ohledně grafu v mobilní aplikaci Aladin. Přijde mi to jako posun SEČL - UTC

**Comment by kukulich** [comment]
Tak pripadne zkus dev verzi.

**Comment by DavidAntonin** [comment]
Zkusil jsem ručně nakopírovat upravený soubor do HA a nyní to po restartu časově sedí.

**Comment by kukulich** [comment]
Releasnuto jako 2.8.2

**Comment by brozikcz** [comment]
jen pro info, pokud se nic nezmenilo, tak aladin od androworks nebere data z CHMU v minulosti se "nepohodli" a presli na data od Noru

**Comment by kukulich** [comment]
Ja mam v planu prozkoumat nove dostupne open data od CHMI
