### ISSUE TITLE
Chyba při přidání integrace

### ISSUE THREAD

**Issue by marekbrezina** [kukulich/home-assistant-aladin-online#3]
Ahoj, díky za integraci. Píšu česky, Aladina asi nikde jinde používat nebudou. 
Přidal jsem repo HACS a restartoval server.
Poté jsem chtěl přidat integraci, ale skončí to chybou, zobrazí se varovný vykřičník a to je vše. V logu nevidím nic kromě obecného varování, že se jedná o neoficiální integraci a může způsobovat nestabilitu.
_WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration aladin_online which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home 

Prosím o radu co zkusit. 
Díky

**Comment by kukulich** [comment]
Bohužel už delší dobu nefunguje zdroj: https://aladinonline.androworks.org/

**Comment by marekbrezina** [comment]
Aj to je škoda. Tak to zavírám.
