### ISSUE TITLE
Aladin - SHMU Slovensko

### ISSUE THREAD

**Issue by vawaver** [kukulich/home-assistant-aladin-online#4]
I would like to ask you to create Aladin - SHMU Slovakia?
Or you can recommend me another source.
Thank you.

**Comment by kukulich** [comment]
@vawaver do you have some API source for slovak Aladin?

**Comment by vawaver** [comment]
> @vawaver do you have some API source for slovak Aladin?

I am very sorry, I do not know anything about programming. So API neither.

**Comment by kukulich** [comment]
It’s not possible without API with Slovak Aladin.

**Comment by vawaver** [comment]
Understand. Thank you.
