### ISSUE TITLE
Add precipitation and clouds forecast

### ISSUE THREAD

**Issue by LadCZ** [kukulich/home-assistant-aladin-online#6]
Hi, this topis is not an issue. Is it possible to add precipitation and clouds forecast data hourly? As it is in the android app?
I intend to us it fo irrigation and solar power output. Thanks

**Comment by kukulich** [comment]
The data should already be there - as a part of weather entity.

**Comment by LadCZ** [comment]
No, just the temperature.
![aladin](https://user-images.githubusercontent.com/105245604/196510325-262f73bf-b54b-4890-87d9-8b015a0858f5.PNG)

**Comment by kukulich** [comment]
@LadCZ Check data in developer tools.

**Comment by LadCZ** [comment]
Thnaks. For others, entities are there but not displayed in the integration. 
![aladin2](https://user-images.githubusercontent.com/105245604/196517229-35d74008-7084-4541-94cd-50525171df6f.PNG)

**Comment by LadCZ** [comment]
closed
