### ISSUE TITLE
The aladin_online custom integration is using deprecated weather forecast

### ISSUE THREAD

**Issue by JoseSVE** [kukulich/home-assistant-aladin-online#9]
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:347
Integration: Weather (documentation, issues)
First occurred: 15:33:37 (1 occurrences)
Last logged: 15:33:37

aladin_online::WeatherEntity implements the `forecast` property or sets `self._attr_forecast` in a subclass of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please create a bug report at https://github.com/kukulich/home-assistant-weather-forecast-for-czech-republic/issues

**Comment by kukulich** [comment]
@JoseSVE What version of aladin integration do you use?

**Comment by JoseSVE** [comment]
Hi, I use  1.4.0 version of Aladin. 

HA
Core: 2023.11.0
Supervisor: 2023.10.1
Operating System: 11.1
Frontend: 20231030.1

**Comment by JoseSVE** [comment]
I will upgrade to the latest version. I thought that it is upgraded automatically and I have the latest version but not.

**Comment by JoseSVE** [comment]
After upgrade to the latest version, the issue was solved.
